name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-14, macos-13]
        xcode: ['15.4', '15.0']
        exclude:
          - os: macos-13
            xcode: '15.4'
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test --enable-code-coverage
    
    - name: Generate code coverage report
      run: |
        xcrun llvm-cov export -format="lcov" .build/debug/ColorHexPackageTests.xctest/Contents/MacOS/ColorHexPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.lcov
        fail_ci_if_error: true

  test-ios:
    name: Test iOS
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    
    - name: Build and test iOS
      run: |
        xcodebuild test \
          -scheme ColorHex \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          -enableCodeCoverage YES

  test-tvos:
    name: Test tvOS
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    
    - name: Build and test tvOS
      run: |
        xcodebuild test \
          -scheme ColorHex \
          -destination 'platform=tvOS Simulator,name=Apple TV,OS=17.5' \
          -enableCodeCoverage YES

  test-watchos:
    name: Test watchOS
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    
    - name: Build watchOS
      run: |
        xcodebuild build \
          -scheme ColorHex \
          -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=10.5'